image:
  file: .gitpod.Dockerfile

ports:
  - port: 5432
    onOpen: ignore
  - port: 6379
    onOpen: ignore
  - port: 8000
    onOpen: open-preview
  - port: 2222
    onOpen: ignore

tasks:
  - name: TCP Tunnel
    command: chisel server --socks5
  - name: SSH Server
    command: |
      [ -f /workspace/dropbear.hostkey ] || dropbearkey -t rsa -f /workspace/dropbear.hostkey
      dropbear -r /workspace/dropbear.hostkey -F -E -s -p 2222 -P ~/dropbear.pid
  - command: |
      mkdir -p ~/.ssh && open ~/.ssh/authorized_keys
      clear
      echo "=============="
      echo " INSTRUCTIONS "
      echo "=============="
      echo ""
      echo "1. Add your public SSH key to ~/.ssh/authorized_keys of this Gitpod workspace"
      echo ""
      echo "2. Install Chisel on your local machine, e.g. curl https://i.jpillora.com/chisel! | bash"
      echo "   see https://github.com/jpillora/chisel"
      echo ""
      echo "3. Connect via SSH from your local machine:"
      echo "   ssh -o ProxyCommand='chisel client $(gp url 8080) stdio:%h:%p' gitpod@localhost -p 2222"
      echo ""
  - name: Redis
    before: redis-server &
  - name: Python
    init: >
      pip install -r ./requirements/local.txt &&
      export $(egrep -v '^#' .envs/.local/.gitpod_postgres | xargs) &&
      export $(egrep -v '^#' .envs/.local/.django | xargs)
    command: >
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
  - name: Frontend (Node.js)
    command: >
      printf "\nRunning 'npm login':\n\n" &&
      npm login &&
      npm install &&
      mkdir -p frontend/static/dist &&
      npm run build
